name: Build Hugo latest

on:
  release:
    types: [published]

  push:
    branches:
      - 'main'
  watch:
    types: [started]

  schedule:
    # Everyday
    - cron:  '0 14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUGO_USERNAME }}
        password: ${{ secrets.DOCKER_HUGO_TOKEN }}

    - name: Login to Coding.net
      uses: docker/login-action@v2
      with:
        registry: eallion-docker.pkg.coding.net/eallion/hugo
        username: ${{ secrets.CODING_HUGO_USERNAME }}
        password: ${{ secrets.CODING_HUGO_TOKEN }}

    - name: Download latest Hugo
      run: |
        mkdir tmp
        bash hugo.sh
        HUGO_VERSION() {
          curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/;s/v//g'
        }
        echo "VERSION=$(HUGO_VERSION)" >> $GITHUB_ENV

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          eallion/hugo:latest
          eallion/hugo:${{ env.VERSION }}
          eallion-docker.pkg.coding.net/eallion/hugo/hugo:latest
          eallion-docker.pkg.coding.net/eallion/hugo/hugo:${{ env.VERSION }}