name: Build Hugo latest

on:
  push:
    branches:
      - 'main'

  watch:
    types: [started]

  schedule:
    # Everyday
    - cron:  '0 14 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

    - name: Get Hugo version
      id: hugo_version
      run: |
        HUGO_VERSION() {
          curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/;s/v//g'
        }
        echo "HUGO_VERSION=$(HUGO_VERSION)" >> $GITHUB_ENV

    - name: Get local version
      id: local_version
      run: |
        LOCAL_VERSION() {
          curl --silent "https://api.github.com/repos/eallion/docker-hugo/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/;s/v//g'
        }
        echo "LOCAL_VERSION=$(LOCAL_VERSION)" >> $GITHUB_ENV

    - if: ${{ env.LOCAL_VERSION }} == ${{ env.HUGO_VERSION }}
      run: echo "No update, skip."

    - name: Checkout
      if: ${{ env.LOCAL_VERSION }} != ${{ env.HUGO_VERSION }}
      uses: actions/checkout@v3

    - name: Set up QEMU
      if: ${{ env.LOCAL_VERSION }} != ${{ env.HUGO_VERSION }}
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      if: ${{ env.LOCAL_VERSION }} != ${{ env.HUGO_VERSION }}
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Login to Docker Hub
      if: ${{ env.LOCAL_VERSION }} != ${{ env.HUGO_VERSION }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUGO_USERNAME }}
        password: ${{ secrets.DOCKER_HUGO_TOKEN }}

    - name: Login to Coding.net
      if: ${{ env.LOCAL_VERSION }} != ${{ env.HUGO_VERSION }}
      uses: docker/login-action@v2
      with:
        registry: eallion-docker.pkg.coding.net/eallion/hugo
        username: ${{ secrets.CODING_HUGO_USERNAME }}
        password: ${{ secrets.CODING_HUGO_TOKEN }}

    - name: Download latest Hugo
      if: ${{ env.LOCAL_VERSION }} != ${{ env.HUGO_VERSION }}
      run: |
        mkdir tmp
        bash hugo.sh

    - name: Build and Push
      if: ${{ env.LOCAL_VERSION }} != ${{ env.HUGO_VERSION }}
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: ./
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          eallion/hugo:latest
          eallion/hugo:${{ env.HUGO_VERSION }}
          eallion-docker.pkg.coding.net/eallion/hugo/hugo:latest
          eallion-docker.pkg.coding.net/eallion/hugo/hugo:${{ env.HUGO_VERSION }}

    - name: Release
      if: ${{ env.LOCAL_VERSION }} != ${{ env.HUGO_VERSION }}
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GH_HUGO_TOKEN }}
        tag_name: v${{ env.HUGO_VERSION }}